version: 2.1
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: user
          RAILS_ENV: test
      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: user_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Bundlerを指定
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: バンドルインストール
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run:
          name: Yarnをインストール
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: DBを待機
          command: dockerize -wait tcp://localhost:5432 -timeout 5m

      - run:
          name: DBを作成
          command: bin/rails db:create

      - run:
          name: データベースをセットアップ
          command: bin/rails db:schema:load --trace

      - run:
          name: rubocop
          command: bundle exec rubocop -c .rubocop.yml

      - run:
          name: Test
          command: ./bin/test

workflows:
  version: 2.1
  rubocop_and_test:
    jobs:
      - build
